type Opt<T> = T | undefined;

/** An object type to describe my information */
export type Me = {
  /** My legal name in different languages. */
  legalName: {
    /** My Pinyin legal name. */
    pinyin: string;

    /** My Chinese legal name. */
    zhCN: string;
  };

  /** My nickname. Used for unofficial purposes. */
  otherNames: {
    [key: string]: string;
  };

  /** My preferred pronouns to reflect my gender. */
  pronouns: 'He/Him/His' | string;

  /** My email addresses. */
  email: {
    /** My person email address. It is always there. */
    personal: string;

    /**
     * Other email addresses, such as campus or working email address, may be unavailable at a time.
     */
    [other: string]: string;
  };

  /** My bios. */
  bio: {
    /** Multiple bios may be used in whatever context. */
    [key: string]: string;
  };

  /** My social media links. */
  socialMedia: {
    /** My GitHub link. */
    github: string;

    /** My LinkedIn link. */
    linkedin: string;

    /** My other social media contact. */
    [other: string]: string | undefined;
  };
};

/**
 * A multilingual field.
 * A English description is asserted. Other languages are optional.
 */
type MultilingualField = {
  [language in 'zhCN']?: string;
} & {
  en: string;
};

/** A project's coworker's info */
type Coworker = {
  displayName: MultilingualField;
  displayEmail?: string;
};

/** A multi-language description for an item. */
type Description = MultilingualField;

/** The kind of a project. */
type ProjectKinds =
  | 'notational composition'
  | 'software'
  | 'machine learning'
  | 'electroacoustic composition';

/** A project is a finished work by myself. */
type Project = {
  /** The name of the project. */
  name: string;

  /**
   * The kind of a project.
   * Could be one of or multiple of
   * notational composition, electroacoustic composition, software, or machine learning project.
   */
  kinds: ProjectKinds[];

  /** The finishing date of the project. Generated by `Date.prototype.toJSON()`. */
  date: string;

  /** The short description of the project. */
  shortDescription?: Description;

  /** The long description of the project in different languages. */
  description: Description;

  /** Any referencing URLs. */
  url: { [key: string]: string };

  /** Any referencing images. */
  img: { [key: string]: string };

  /** Any coworkers that contributes to this project. */
  coworkers: { [name: string]: Coworker };
};

/** Project list type. */
export type Projects = Project[];

/** Fetch projects from AWS S3 server. */
export const fetchProjects = async () => {
  const res = await fetch(
    'https://int0thewind.s3.us-east-2.amazonaws.com/projects.json'
  );
  const data: Projects = await res.json();
  return data.sort((a, b) => (new Date(a.date) < new Date(b.date) ? 1 : -1));
};

/** Fetch the info about me from AWS S3 server. */
export const fetchMe = async () => {
  const res = await fetch(
    'https://int0thewind.s3.us-east-2.amazonaws.com/me.json'
  );
  const data: Me = await res.json();
  return data;
};

/** The AWS S3 link to my personal curriculum vitae. */
export const cvLink = 'https://int0thewind.s3.us-east-2.amazonaws.com/cv.pdf';

/** The AWS S3 link to my personal avatar. */
export const avatarLink = '';
