/** An object type to describe my information */
export type Me = {
  /** My legal name in different languages. */
  legalName: {
    /** My Pinyin legal name. */
    pinyin: string,

    /** My Chinese legal name. */
    zhCN: string,
  },

  /** My nickname. Used for unofficial purposes. */
  otherNames: {
    [key: string]: string,
  },

  /** My preferred pronouns to reflect my gender. */
  pronouns: 'He/Him/His' | string,

  /** My email addresses. */
  email: {
    /** My person email address. It is always there. */
    personal: string,

    /**
     * Other email addresses, such as campus or working email address, may be unavailable at a time.
     * Set them to be nondeterministic.
     */
    [other: string]: string
  },

  /** My bios. */
  bio: {
    /** Multiple bios may be used in whatever context. Set them to be nondeterministic. */
    [key: string]: string,
  },

  /** My social media links. */
  socialMedia: {
    /** My GitHub link. */
    github: string,

    /** My LinkedIn link. */
    linkedin: string,

    /** My other social media contact. Set them to be nondeterministic. */
    [other: string]: string,
  },
};

/** A project's coworker's info */
export type Coworker = {
  displayName: {
    en: string,
    [language: string]: string,
  },
  displayEmail?: string,
};

/** A multi-language description for an item. */
export type Description = {
  en: string,
  [language: string]: string,
};

/** A project is a finished work by myself. */
export type Project = {
  /** The name of the project. */
  name: string,

  /**
   * The kind of a project.
   * Could be one of or multiple of
   * notational composition, electroacoustic composition, software, or machine learning project.
   */
  kinds: string[],

  /** The finishing date of the project. Generated by `Date.prototype.toJSON()`. */
  date: string,

  /** The short description of the project. */
  shortDescription?: Description,

  /** The long description of the project in different languages. */
  description: Description,

  /** Any referencing URLs. */
  url: { [key: string]: string },

  /** Any referencing images. */
  img: { [key: string]: string },

  /** Any coworkers that contributes to this project. */
  coworkers: { [name: string]: Coworker }
};

/** Project list type. */
export type Projects = Project[];

/** The AWS S3 link to my personal projects JSON file. */
export const projectsJsonLink = 'https://int0thewind.s3.us-east-2.amazonaws.com/projects.json';

/** The AWS S3 link to my personal info JSON file. */
export const meJsonLink = 'https://int0thewind.s3.us-east-2.amazonaws.com/me.json';

/** The AWS S3 link to my personal curriculum vitae. */
export const cvLink = '';

/** The AWS S3 link to my personal avatar. */
export const avatarLink = '';
