/** A project's coworker's info */
export type Coworker = {
  email?: string,
};

export type Description = {
  en: string,
  [language: string]: string,
};

/** A project is a finished work by myself. */
export type Project = {
  /** The name of the project. */
  name: string,

  /**
   * The kind of a project.
   * Could be one of or multiple of
   * notational composition, electroacoustic composition,software, or machine learning project.
   */
  kinds: string[],

  /** The finishing date of the project. Generated by `Date.prototype.toJSON()`. */
  date: string,

  /** The short description of the project. */
  shortDescription?: Description,

  /** The long description of the project in different languages. */
  description: Description,

  /** Any referencing URLs. */
  url: { [key: string]: string },

  /** Any referencing images. */
  img: { [key: string]: string },

  /** Any coworkers that contributes to this project. */
  coworkers: { [name: string]: Coworker }
};

/** Project list type.. */
export type Projects = Project[];
